apiVersion: v1
kind: ConfigMap
metadata:
  name: stonebank-config
  labels:
    app: stonebank
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stonebank
  SPRING_DATASOURCE_USERNAME: stonebank
  SPRING_DATASOURCE_PASSWORD: stonebank
  SPRING_KAFKA_CONSUMER_BOOTSTRAPSERVERS: kafka:9092
  SPRING_KAFKA_PRODUCER_BOOTSTRAPSERVERS: kafka:9092
  SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
  SERVER_PORT: "8080"
  SPRING_CLOUD_CONSUL_CONFIG_ENABLED: "true"
  SPRING_CLOUD_CONSUL_ENABLED: "true"
  SPRING_CLOUD_CONSUL_HOST: "consul-consul-server"
  SPRING_CLOUD_CONSUL_PORT: "8500"
  SPRING_CLOUD_CONSUL_CONFIG_PREFIX: "config"